// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolData;

#nullable disable

namespace SchoolData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEscolar.Models.Class", b =>
                {
                    b.Property<int>("IdClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClass"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("IdClass");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCourse"));

                    b.Property<int>("ClassIdClass")
                        .HasColumnType("int");

                    b.Property<int>("GroupIdGradeGroup")
                        .HasColumnType("int");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("IdCourse");

                    b.HasIndex("ClassIdClass");

                    b.HasIndex("GroupIdGradeGroup");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SistemaEscolar.Models.EmergencyContact", b =>
                {
                    b.Property<int>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContact"));

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentsIdStudent")
                        .HasColumnType("int");

                    b.HasKey("IdContact");

                    b.HasIndex("StudentsIdStudent");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<DateTime>("BornDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEmployee");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Group", b =>
                {
                    b.Property<int>("IdGradeGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGradeGroup"));

                    b.Property<int>("Grade")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<string>("GroupClass")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTutor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TutorIdTutor")
                        .HasColumnType("int");

                    b.HasKey("IdGradeGroup");

                    b.HasIndex("TutorIdTutor");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Pay", b =>
                {
                    b.Property<int>("IdPay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPay"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPayType")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<DateTime>("InscriptionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PayTypesIdPayType")
                        .HasColumnType("int");

                    b.Property<int>("StudentsIdStudent")
                        .HasColumnType("int");

                    b.HasKey("IdPay");

                    b.HasIndex("PayTypesIdPayType");

                    b.HasIndex("StudentsIdStudent");

                    b.ToTable("Pays");
                });

            modelBuilder.Entity("SistemaEscolar.Models.PayType", b =>
                {
                    b.Property<int>("IdPayType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPayType"));

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPayType");

                    b.ToTable("PayTypes");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<int>("Age")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdStudent");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SistemaEscolar.Models.StudentCourse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CoursesIdCourse")
                        .HasColumnType("int");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCource")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentsIdStudent")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CoursesIdCourse");

                    b.HasIndex("StudentsIdStudent");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Teacher", b =>
                {
                    b.Property<int>("IdTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeacher"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("IdTeacher");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTutor"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HighSystem")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("IdTutor");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Course", b =>
                {
                    b.HasOne("SistemaEscolar.Models.Class", "Class")
                        .WithMany("IdCourse")
                        .HasForeignKey("ClassIdClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEscolar.Models.Group", "Group")
                        .WithMany("IdCourse")
                        .HasForeignKey("GroupIdGradeGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEscolar.Models.Teacher", "Teachers")
                        .WithMany("IdCourse")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Group");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SistemaEscolar.Models.EmergencyContact", b =>
                {
                    b.HasOne("SistemaEscolar.Models.Student", "Students")
                        .WithMany("IdContact")
                        .HasForeignKey("StudentsIdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Group", b =>
                {
                    b.HasOne("SistemaEscolar.Models.Tutor", "Tutor")
                        .WithMany("Groups")
                        .HasForeignKey("TutorIdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Pay", b =>
                {
                    b.HasOne("SistemaEscolar.Models.PayType", "PayTypes")
                        .WithMany("IdPay")
                        .HasForeignKey("PayTypesIdPayType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEscolar.Models.Student", "Students")
                        .WithMany("IdPay")
                        .HasForeignKey("StudentsIdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayTypes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SistemaEscolar.Models.StudentCourse", b =>
                {
                    b.HasOne("SistemaEscolar.Models.Course", "Courses")
                        .WithMany("IdStudentCourse")
                        .HasForeignKey("CoursesIdCourse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEscolar.Models.Student", "Students")
                        .WithMany("IdStudentCourse")
                        .HasForeignKey("StudentsIdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Teacher", b =>
                {
                    b.HasOne("SistemaEscolar.Models.Employee", "Employee")
                        .WithMany("teachers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Tutor", b =>
                {
                    b.HasOne("SistemaEscolar.Models.Employee", "Employee")
                        .WithMany("tutors")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Class", b =>
                {
                    b.Navigation("IdCourse");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Course", b =>
                {
                    b.Navigation("IdStudentCourse");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Employee", b =>
                {
                    b.Navigation("teachers");

                    b.Navigation("tutors");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Group", b =>
                {
                    b.Navigation("IdCourse");
                });

            modelBuilder.Entity("SistemaEscolar.Models.PayType", b =>
                {
                    b.Navigation("IdPay");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Student", b =>
                {
                    b.Navigation("IdContact");

                    b.Navigation("IdPay");

                    b.Navigation("IdStudentCourse");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Teacher", b =>
                {
                    b.Navigation("IdCourse");
                });

            modelBuilder.Entity("SistemaEscolar.Models.Tutor", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
